# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: default
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ShadowySpirits
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories: 1000
          repositories_forks: yes
          repositories_affiliations: ""
          config_octicon: yes
          config_timezone: Asia/Hong_Kong
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          base_indepth: yes
          repositories: 1000
          repositories_forks: yes
          repositories_affiliations: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - name: Cache github stats dark mode
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://github-readme-stats.lv5.moe/api?username=ShadowySpirits&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&hide_border=true&theme=dark'
          method: 'GET'
          retry: 3
      - name: Cache github stats light mode
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://github-readme-stats.lv5.moe/api?username=ShadowySpirits&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&hide_border=true&theme=default'
          method: 'GET'
          retry: 3
      - name: Cache language stats dark mode
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://github-readme-stats.lv5.moe/api/top-langs?username=ShadowySpirits&hide_title=false&layout=compact&card_width=320&langs_count=5&hide_border=true&theme=dark'
          method: 'GET'
          retry: 3
      - name: Cache language stats light mode
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://github-readme-stats.lv5.moe/api/top-langs?username=ShadowySpirits&hide_title=false&layout=compact&card_width=320&langs_count=5&hide_border=true&theme=default'
          method: 'GET'
          retry: 3

